# Generated by Django 2.2.6 on 2019-10-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('to', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('office', models.IntegerField(max_length=10)),
                ('financial_group', models.CharField(max_length=20)),
                ('financial', models.CharField(max_length=20)),
                ('value', models.IntegerField(max_length=10)),
            ],
        ),
    ]
