# Generated by Django 2.2.6 on 2019-10-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20191031_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='office',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='value',
            field=models.IntegerField(),
        ),
    ]
