# Generated by Django 2.2.6 on 2019-10-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_auto_20191031_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='table',
            old_name='Table_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Table_financial',
            new_name='financial',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Table_financial_group',
            new_name='financial_group',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Table_month',
            new_name='month',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Table_office',
            new_name='office',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Table_to',
            new_name='to',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='Table_value',
            new_name='value',
        ),
        migrations.AlterModelTable(
            name='table',
            table=None,
        ),
    ]
